name: drkmode_app
description: The official app for Drk Mode Podcast.
homepage: 'https://drkmodepodcast.com'
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  datetime_picker_formfield: ^2.0.0
  drkmode_common:
    path: ../common
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Barbaro
      fonts:
        - asset: assets/barbaro.ttf

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
