name: drkmode_server
description: The server that powers the Drk Mode app.
version: 0.0.0
homepage: 'https://drkmodepodcast.com'
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  drkmode_common:
    path: ../common
  shelf: ^1.2.0
  shelf_router: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.1
  pedantic: ^1.11.1
  shelf_router_generator: ^1.0.1
