name: drkmode_common
description: Common code shared between the Drk Mode app and server.
version: 0.0.0
homepage: 'https://drkmodepodcast.com'
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
