name: drkmode_common
description: Common code shared between the Drk Mode app and server.
version: 0.0.0
homepage: 'https://drkmodepodcast.com'
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
